/*
# Create public booking request records

1. New Tables
- `booking_requests` stores reservation requests submitted from the public booking form.
- `id` is the internal unique identifier.
- `confirmation_code` is the customer-facing reservation code generated by the app.
- `customer_name` and `contact_number` store the details needed to confirm the request.
- `booking_date`, `start_time`, `duration_hours`, and `courts` store the requested schedule.
- `total_amount` stores the calculated Philippine-peso amount shown to the customer.
- `payment_method` and `payment_reference` store the selected bank and optional transfer reference.
- `status` tracks whether the request is pending, confirmed, or cancelled.
- `created_at` records when the request was submitted.

2. Security
- Row-level security is enabled.
- Anonymous and signed-in visitors can submit booking requests without creating an account.
- Booking rows are not publicly readable, editable, or deletable because they contain customer contact and payment details.
- The app shows the generated confirmation code immediately after a successful submission.

3. Important Notes
- The booking flow is a request-and-confirm process; payment is made through the displayed GoTyme Bank or MariBank QR code.
- Prices are constrained to the business rates used by the booking page.
*/

CREATE TABLE IF NOT EXISTS public.booking_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  confirmation_code text NOT NULL UNIQUE,
  customer_name text NOT NULL CHECK (char_length(customer_name) BETWEEN 2 AND 120),
  contact_number text NOT NULL CHECK (char_length(contact_number) BETWEEN 7 AND 30),
  booking_date date NOT NULL,
  start_time time NOT NULL,
  duration_hours integer NOT NULL CHECK (duration_hours BETWEEN 1 AND 24),
  courts integer NOT NULL CHECK (courts BETWEEN 1 AND 2),
  total_amount integer NOT NULL CHECK (total_amount BETWEEN 150 AND 19200),
  payment_method text NOT NULL CHECK (payment_method IN ('GoTyme Bank', 'MariBank')),
  payment_reference text CHECK (payment_reference IS NULL OR char_length(payment_reference) <= 100),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.booking_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can submit booking requests" ON public.booking_requests;
CREATE POLICY "Public can submit booking requests"
  ON public.booking_requests FOR INSERT
  TO anon, authenticated
  WITH CHECK (status = 'pending');

DROP POLICY IF EXISTS "Booking requests are not publicly readable" ON public.booking_requests;
CREATE POLICY "Booking requests are not publicly readable"
  ON public.booking_requests FOR SELECT
  TO anon, authenticated
  USING (false);

DROP POLICY IF EXISTS "Booking requests are not publicly editable" ON public.booking_requests;
CREATE POLICY "Booking requests are not publicly editable"
  ON public.booking_requests FOR UPDATE
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS "Booking requests are not publicly deletable" ON public.booking_requests;
CREATE POLICY "Booking requests are not publicly deletable"
  ON public.booking_requests FOR DELETE
  TO anon, authenticated
  USING (false);

CREATE INDEX IF NOT EXISTS booking_requests_date_idx
  ON public.booking_requests (booking_date, start_time);
