/*
# Add payment confirmation code and receipt storage

1. New columns on public.booking_requests
- payment_code: generated automatically when a booking is confirmed (fully paid). Unique code the customer uses as proof of payment.
- receipt_path: path to the customer's uploaded payment receipt screenshot in Supabase Storage.

2. Trigger
- BEFORE UPDATE trigger generates a payment_code automatically when status transitions to 'confirmed'.
- Format: 8PF-PAY-XXXXXXXX (8 random hex characters).
- Only generates when payment_code is NULL and status is changing to confirmed.
- Function is SECURITY DEFINER so it can set payment_code even though the admin UPDATE grant is restricted to the status column.

3. Storage
- Create private bucket 'receipts' for payment receipt uploads.
- Anon can upload (INSERT) to the bucket so customers can attach receipts from the public booking form.
- Only authenticated (admin) can read (SELECT) receipts — customer payment screenshots are private.
- No public read access.

4. Security notes
- Receipts are only accessible via signed URLs generated by an authenticated admin session.
- The trigger function runs as its owner (SECURITY DEFINER) to bypass the column-level UPDATE restriction on payment_code.
- Customer contact and payment details remain protected as before.
*/

ALTER TABLE public.booking_requests
  ADD COLUMN IF NOT EXISTS payment_code text UNIQUE,
  ADD COLUMN IF NOT EXISTS receipt_path text;

CREATE OR REPLACE FUNCTION public.generate_payment_code()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NEW.status = 'confirmed' AND (OLD.status IS DISTINCT FROM 'confirmed') AND NEW.payment_code IS NULL THEN
    NEW.payment_code = '8PF-PAY-' || upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 8));
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_payment_code_on_confirm ON public.booking_requests;
CREATE TRIGGER set_payment_code_on_confirm
  BEFORE UPDATE ON public.booking_requests
  FOR EACH ROW
  EXECUTE FUNCTION public.generate_payment_code();

INSERT INTO storage.buckets (id, name, public)
  VALUES ('receipts', 'receipts', false)
  ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public can upload receipts" ON storage.objects;
CREATE POLICY "Public can upload receipts"
  ON storage.objects FOR INSERT
  TO anon, authenticated
  WITH CHECK (bucket_id = 'receipts');

DROP POLICY IF EXISTS "Admins can read receipts" ON storage.objects;
CREATE POLICY "Admins can read receipts"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'receipts');
